name: Healthcheck

on:
  schedule:
    # "At 00:00", so once a day.
    - cron: "0 0 * * *"

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Health check
        uses: jtalk/url-health-check-action@b716ccb6645355dd9fcce8002ce460e5474f7f00
        with:
          url: ${{ secrets.RENDER_URL }}/health
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
