name: Healthcheck

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  schedule:
    # "At every fifth minute"
    - cron: "*/5 * * * *"

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Health check
        uses: jtalk/url-health-check-action@b716ccb6645355dd9fcce8002ce460e5474f7f00
        with:
          url: https://full-stack-open-pokedex-eztk.onrender.com/health
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
