name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    if: ${{ !contains(join(github.event.commits.*.message), '#skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Send successful deployment notification
        if: ${{ success() }}
        # commit for v2.2.1
        uses: rjstone/discord-webhook-notify@c2597273488aeda841dd1e891321952b51f7996f
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: GitHub
          # text: Below this normal-looking message is an embed!
          severity: info # only to make sure the embed is added
          title: A new version of Pokedex deployed
          # description: "This is a ***SuPeR custom*** description. I hope it looks good."
          # details: not needed because we overrode default description.
          # footer: This embed was brought to you by the letter R and the number 4.
  tag_release:
    if: ${{ !contains(join(github.event.commits.*.message), '#skip') }}
    runs-on: ubuntu-latest
    needs: [simple_deployment_pipeline]
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        # Use a specific hash instead of version number to be sure that the underlying code can't be changed.
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'
          DRY_RUN: false